# Generated by Django 3.1.3 on 2020-11-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part Time')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
