# Generated by Django 3.1.3 on 2020-11-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='webiste',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to='apply/'),
        ),
    ]
